# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write  # Изменено с read на write!
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x
          
      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check
      
      - name: Build Fresh app
        run: deno task build
        
      - name: Check build output
        run: |
          echo "Checking build output:"
          ls -la _fresh/ || echo "_fresh directory not found"
          if [ -f "_fresh/snapshot.json" ]; then
            echo "✅ snapshot.json exists"
          else
            echo "❌ snapshot.json not found"
            exit 1
          fi
        
      - name: Run linter
        run: deno lint
        
      - name: Run tests
        run: deno test -A
        
      - name: Commit build artifacts (только для main branch)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _fresh/
          if ! git diff --staged --quiet; then
            git commit -m "🤖 Auto-build: Update Fresh build artifacts [skip ci]"
            git push
            echo "✅ Build artifacts committed and pushed"
          else
            echo "ℹ️ No changes to commit"
          fi
